// <auto-generated />
using System;
using GarrysMod.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GarrysMod.Migrations
{
    [DbContext(typeof(ModContext))]
    [Migration("20251205222621_ChangeLongToInt")]
    partial class ChangeLongToInt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("GarrysMod.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PopularityMeter")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Weapon",
                            PopularityMeter = 9
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tool",
                            PopularityMeter = 8
                        },
                        new
                        {
                            Id = 3,
                            Name = "Vehicle",
                            PopularityMeter = 3
                        });
                });

            modelBuilder.Entity("GarrysMod.Models.Creator", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MapId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("MapId");

                    b.ToTable("Creators");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            IsAdmin = true,
                            Password = "password",
                            Username = "Facepunch"
                        },
                        new
                        {
                            ID = 2,
                            IsAdmin = false,
                            Password = "password",
                            Username = "Valve"
                        });
                });

            modelBuilder.Entity("GarrysMod.Models.GarrysItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MapId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("MapId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 1,
                            CreatorId = 1,
                            Description = "A physics manipulation device.",
                            MapId = 1,
                            Title = "Gravity Gun"
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 2,
                            CreatorId = 2,
                            Description = "A versatile tool for editing objects.",
                            MapId = 2,
                            Title = "Tool Gun"
                        });
                });

            modelBuilder.Entity("GarrysMod.Models.Map", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SizeInMB")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Maps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The classic sandbox testing map",
                            Name = "gm_construct",
                            SizeInMB = 45.25
                        },
                        new
                        {
                            Id = 2,
                            Description = "The classic sandbox testing map containing all deleted features",
                            Name = "gm_construct_v13_beta",
                            SizeInMB = 245.25
                        });
                });

            modelBuilder.Entity("GarrysMod.Models.Creator", b =>
                {
                    b.HasOne("GarrysMod.Models.Map", null)
                        .WithMany("Creators")
                        .HasForeignKey("MapId");
                });

            modelBuilder.Entity("GarrysMod.Models.GarrysItem", b =>
                {
                    b.HasOne("GarrysMod.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GarrysMod.Models.Creator", "Creator")
                        .WithMany("Items")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GarrysMod.Models.Map", "Map")
                        .WithMany()
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Creator");

                    b.Navigation("Map");
                });

            modelBuilder.Entity("GarrysMod.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("GarrysMod.Models.Creator", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("GarrysMod.Models.Map", b =>
                {
                    b.Navigation("Creators");
                });
#pragma warning restore 612, 618
        }
    }
}
